name       : python-fakefs
version    : 3.5.8
release    : 2
source     :
    - https://pypi.io/packages/source/p/pyfakefs/pyfakefs-3.5.8.tar.gz : 8cd2270d65d3316dd4dc6bb83242df2e0990d27605209bc16e8041bcc0956961
license    : Apache-2.0
component  : programming.python
summary    : pyfakefs implements a fake file system that mocks the Python file system modules
description: |
    pyfakefs implements a fake file system that mocks the Python file system modules. Using pyfakefs, your tests operate on a fake file system in memory without touching the real disk. The software under test requires no modification to work with pyfakefs.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
