name       : python-fakefs
version    : 4.5.6
release    : 9
source     :
    - https://github.com/jmcgeheeiv/pyfakefs/archive/refs/tags/v4.5.6.tar.gz : 71bc8e5554d132fe39ec0253f500de94c0d1d94a0772f47df14454b86d033598
homepage   : https://github.com/jmcgeheeiv/pyfakefs
license    : Apache-2.0
component  : programming.python
summary    : pyfakefs implements a fake file system that mocks the Python file system modules
description: |
    pyfakefs implements a fake file system that mocks the Python file system modules. Using pyfakefs, your tests operate on a fake file system in memory without touching the real disk. The software under test requires no modification to work with pyfakefs.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test 
